### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fardarter**
Think that mocking people's backgrounds is really unwelcoming.

### CODE REVIEW

**Comment by n1c** [comment]
I have mixed feelings for a pr like this. I agree that people shouldn't be making offensive comments about education & vocation. But they shouldn't be making offensive comments about _anything_ and trying to codify _everything_ will lead us into a weird cat & mouse game.

Personally I think that if this is related to a specific incident - it can probably already be handled by the code of conduct. I see there's already some thumbs, so happy to discuss more!

**Comment by fardarter** [comment]
> I have mixed feelings for a pr like this. I agree that people shouldn't be making offensive comments about education & vocation. But they shouldn't be making offensive comments about _anything_ and trying to codify _everything_ will lead us into a weird cat & mouse game.
> 
> Personally I think that if this is related to a specific incident - it can probably already be handled by the code of conduct. I see there's already some thumbs, so happy to discuss more!

It's related to people's ongoing mockery of the humanities (at at times other professions). 

We have people from all backgrounds coming to ZATech.

Many people came to tech through other paths and the skills and knowledge they gained doing so is valuable. 

I have no problem with discussion about the role of the humanities and the university in life, if it's respectful. Same for critiques of fields. 

But the constant "hur dur, humanities is dumb and everyone who does it is a charlatan" isn't respectful.

**Comment by fardarter** [comment]
> I mean, the true goal of this isn't aimed at changing people and make everyone nice. It is aimed at providing a basis to persecute those who arguably don't comply with a given notion of what a certain member deems acceptable conduct, punish them for their sins, and turn them into examples to enforce a chilling effect on the community.

OK, so, no, that's not the true goal. Actually, it's about making a space where people are respected. But it's good that you're reading my mind and attributing the worst faith to me. Let me return the favour.

I understand that you wish to be free of the burden of showing people respect, but I see now particular reason why anyone should support that. All this talk of persecution (what an utterly ridiculous word to introduce) is merely IMO your reaction to being asked to make an effort to treat others with dignity. 

> In my opinion the point in case where this stemmed from was in the general vein of discourse, on we tend to have every day on zatech in one way or another.

Yes, it's bad and I want to make it unwelcome. If you don't share that opinion, fine. I hope that more people agree with me than you and that you lose -- democratically. 

What's the plan otherwise? Complete freedom to turn the place into 4chan like some people want (and like some private channels operate)? A community has to have standards.

> Be it over disagreement over the stock market, finance, renewables, are we really going to create a never ending list of things to add to the CoC in individuality based on one knee jerk reaction?

These are not "disagreements" and these are not random topics. These are constant trollings. There's nothing respectful or good faith about them. They're designed to get a reaction because people think it's funny to mock others. They're designed to make people feel bad if they're a member of the category being mocked.

They also make whole categories of people feel small and unwelcome. It's not like ZATech is a particularly diverse space -- and I'd bet the status quo you're defending is part of why. The demographics of the space appear on the surface to be _embarrassing_ -- though without stats it's hard to say for sure. 

> In the real world people discriminate on vocation all the time, in work place hiring, in academia, in jest. It's reall shooting ourselves in the foot if we allow us to become yes men who never challenge each other and instinctually jump to the CoC where things could be resolved through debate or humor.

This is the real world. Online is part of the real world. And we make the real world good by suppressing nonsense. You are welcome to challenge things _respectfully_. There's literally no moral reason to permit bad faith challenges. It makes the possibility of having real conversations _worse_.

> What counts as education btw? If I do a course on eMacs can I reach out because I don't like that someone made a bad joke about Vim being better?

Edge cases always have to be dealt with using judgment. I think _ongoing and relentless_ mockery of one third of the traditional university is so staggeringly obviously not an edge case that you'd be forced to admit it if you ever had to state outright your case instead of by insinuation. 

It's just pig ignorant. It's the sort of thing first years do and everyone else has learned to be embarrassed about.

> Do we really want to create an oppressive and abusive CoC concept because they tend to believe that it can only ever oppress those we deem undesirable. But unless you're the one doing the oppression, nothing ensures that the rules only apply to those you don't like.

Again, "oppressive" and "abusive" are ridiculous ideas to even advance here. Truly the art of stirring the moral panic is reaching its fullest realisation here. 

And yes nothing guarantees that the rules won't come back and bite me. That's just a fact about power. 

But the admins are extremely careful about punishment in this space, even with the existing rules, is managed with a light touch. I see no reason to suspect that wouldn't continue. 

But at least with this they could ask you to stop.

**Comment by fardarter** [comment]
> you have used history before to enact certain ruling on slack, so let's do the same here. You talk about ridiculousness but actively attempted to get someone punished for a hate crime which was not even directed at you, but another user over a symbol which when used in context is not hateful. So I'd be careful introducing the concept of misdirected persecution here. You also actively use clown emojis on people while also raising complaints of emojis used on you.

The pepe symbol was obviously directed at me from the context. It is well known I consider it a hate symbol. The person using it _knows_ this. They've been disciplined for it in the past. It makes an absolute mockery of everyone's reading comprehension to pretend otherwise. 

> You also actively use clown emojis on people while also raising complaints of emojis used on you.

I've completely stopped. As for why I used it in the past -- because _there has been literally no way of getting anyone to stop peppering nearly everything I say with insulting stuff_. That goodness I found _something_ that made you even take a half step back. It took _months_ of harassment for me to even start.

> But yes, no point in engaging this topic further, this is not the place for personal mudslinging, but I wanted to raise what I saw as the motivations for this

Then why did you start the personal mudslinging by claiming I'm trying to "persecute" you? Imagine thinking _that_ isn't raising the emotional bar.

**Pull request closed without merging**
