### PR TITLE
Bad faith clause on reporting in CoC channel

### PR DESCRIPTION
**Pull request by fardarter**

### CODE REVIEW

**Comment by fardarter** [comment]
> Strong -1.
> 
> It is not reasonable to require that the reporter directly inform or seek resolution with the reported user, or to consider failure to do so to be bad-faith or harassing behaviour.
> 
> In many cases of abuse (such as sexual harassment, PTSD, stalking, violent threats, or blackmail) directly confronting an abuser can expose the target to significant further abuse, trauma, or danger. The safety of reporting users should always take first priority in reporting processes, and direct contact with reported users should never be required.
> 
> The existing guidelines should be sufficient for the team to handle bad-faith reports.

The requirement states that this is only where safe to do so. Why would this not cover the above cases?

I don't believe, because of how you and I have both recently been treated in CoC, that this suffices. CoC should not a place to air grievances as loudly as possible, and making a thread about someone where their friends dump into is in front of the whole community is harassment. 

Literally just asking those in the position (ie, not people who cannot do it safely) to do so to make an attempt to resolve the issue before blaring it out to everyone.

**Comment by PiDelport** [comment]
> The requirement states that this is only where safe to do so "(where, in good faith, it is safe for the reporter to do so)". Why would this not cover the above cases?

Without a working definition of exactly what "safe" means, this doesn't really helps: it effectively puts the burden on the target to demonstrate how and why the reporter is not safe to engage, rather than treating it as axiomatic that if someone has to report a violation, their attempts at reasonable and safe engagement have already failed.

> I don't believe, because of how you and I have both recently been treated in CoC, that this suffices. CoC should not a place to air grievances as loudly as possible, and making a thread about someone where their friends dump into is in front of the whole community is harassment.

This is true, but the existing language about rejecting bad-faith reports should already cover that. It would not be okay to require the reporters in question to engage with you or me if those reports were meaningful (or for any other reason, really).

> Literally just asking those in the position (ie, not people who cannot do it safely) to do so to make an attempt to resolve the issue before blaring it out to everyone.

It's sufficient to treat this like any other harassment: if anyone persists in making bad-faith reports, the moderation team can take whatever action they deem necessary to stop that behaviour, without forcing any interaction between unwilling parties.

**Comment by fardarter** [comment]
> Without a working definition of exactly what "safe" means, this doesn't really helps: it effectively puts the burden on the target to demonstrate how and why the reporter is not safe to engage, rather than treating it as axiomatic that if someone has to report a violation, their attempts at reasonable and safe engagement have already failed.

My view would be that this turns on "if someone _has_ to report a", whereas what we're seeing here is people who do not _have_ to report, but are choosing to do so. I would argue that including the phrase allows people to read a presumption in that if they do not feel safe they will be protected, but I'd be happy to try work a re-phrasal that makes this more explicit -- my original intuition is that the paragraph following would be sufficient, as well as the offering that admins would be available in private.

I do think we should have a norm and a rule of attempting to resolve some disputes outside of the CoC. Perhaps there should be a different section where this is outlined? I'm happy to try rework the suggestion if yes. On the other hand, having something like that implies that we're differentiating between things that need to/should go through that process and things which don't.

What I will say about the direct-to-CoC route is that I don't think it's reasonable to assume in advance that 8000 people should be notified about someone's negative opinion of someone, or that that person must suffer that indignity quietly to preserve the peace. I don't think it's sufficient that it's merely the case that someone is ignored for putting their grievance out in front of so many people, as it is humiliating and upsetting to have an entire community read negative commentary about you. I think we need something more proactive than that.

**Comment by n1c** [comment]
Looks like this issue has stalled out and isn't going to be merged so I'm going to close the PR unless there's impetus to revive it.

**Pull request closed without merging**
